resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

secretGenerator:
- envs:
  - do-api-token.env
  name: do-api-token
