---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-databases-digitalocean-com-v1alpha1-databaseclusterreference
  failurePolicy: Fail
  name: vdatabaseclusterreference.kb.io
  rules:
  - apiGroups:
    - databases.digitalocean.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseclusterreferences
  sideEffects: None
