# permissions for end users to view databaseclusterreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclusterreference-viewer-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseclusterreferences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseclusterreferences/status
  verbs:
  - get
