# permissions for end users to edit databaseuserreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseuserreference-editor-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseuserreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseuserreferences/status
  verbs:
  - get
