# permissions for end users to edit databaseclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasecluster-editor-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseclusters/status
  verbs:
  - get
