# permissions for end users to edit databaseclusterreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclusterreference-editor-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseclusterreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseclusterreferences/status
  verbs:
  - get
