# permissions for end users to view databaseuserreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseuserreference-viewer-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseuserreferences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseuserreferences/status
  verbs:
  - get
