# permissions for end users to edit databaseusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseuser-editor-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databaseusers/status
  verbs:
  - get
