name: release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tag and release to create'
        # Input has to be provided for the workflow to run
        required: true
env:
  GITHUB_ENV: ".env"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}
      - name: Build and push docker image
        run: make docker-build docker-push
        env:
          IMG_TAG: ${{ github.event.inputs.tag }}
      - name: Build and commit manifests
        run: |
          echo 'access-token=<your api token here>' > config/manager/do-api-token.env
          make release-manifests
        env:
          IMG_TAG: ${{ github.event.inputs.tag }}
      - name: Commit manifests
        uses: EndBug/add-and-commit@998652d28d7702d095d40f52ae42982a80ae8c7d
        with:
          message: "Create release manifests for ${{ github.event.inputs.tag }}"
          add: "releases/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: find target commit to tag
        run: |
          sha=$(git rev-parse HEAD)
          echo "TARGET_SHA=$sha" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ env.TARGET_SHA }}
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
